apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-crt-configmap
data:
  nginx-selfsigned.crt: |
    -----BEGIN TRUSTED CERTIFICATE-----
    MIIEGTCCAwGgAwIBAgIUPsLkfFWdlMyfMvvhY6DqxPfqotgwDQYJKoZIhvcNAQEL
    BQAwgZsxCzAJBgNVBAYTAk1YMRIwEAYDVQQIDAlDaGlodWFodWExEjAQBgNVBAcM
    CUNoaWh1YWh1YTEOMAwGA1UECgwFSW50ZWsxDjAMBgNVBAsMBUludGVrMQ4wDAYD
    VQQDDAVKZXN1czE0MDIGCSqGSIb3DQEJARYlamVzdXNjYXJtb25hMTAyGxtnGzYb
    NBtbQxtbQxtbQxtbQxtbQzAeFw0yMzA0MTEwMDA2MzlaFw0yNDA0MTAwMDA2Mzla
    MIGbMQswCQYDVQQGEwJNWDESMBAGA1UECAwJQ2hpaHVhaHVhMRIwEAYDVQQHDAlD
    aGlodWFodWExDjAMBgNVBAoMBUludGVrMQ4wDAYDVQQLDAVJbnRlazEOMAwGA1UE
    AwwFSmVzdXMxNDAyBgkqhkiG9w0BCQEWJWplc3VzY2FybW9uYTEwMhsbZxs2GzQb
    W0MbW0MbW0MbW0MbW0MwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD3
    ww8uwDr2txeGkv9yHik9pBtwkyGgauYin5BH5YMCAr9qd6iHQv1nyxFo/z8eNSSm
    M83B3ndOP7tl0Baz1DxDS7Xp/4tZFZ1k63az5xDucrO+/gb7hmtTbEdMvz+3yCNZ
    rZtK42JfHd5k1dkN/JnlLtNDHg7CziiV/BA2AvRuHcb428wAsOGVuefZvbXqdtaF
    TljwuAsRw4+2KIxh/FecH/MLTHp7uWcCzfE+0NIMwVwYEax+2DMTnjuEFA5m3bat
    nrrOwoRKmmICX7kciLeFpa7mvDigSWuglgIMEr4tb0GtNm3IE9EgqjFL/HeB59wO
    /QfFnvelBdKSXnk/sERzAgMBAAGjUzBRMB0GA1UdDgQWBBSk56FQhUQyANALV9Un
    mxdLtlFuATAfBgNVHSMEGDAWgBSk56FQhUQyANALV9UnmxdLtlFuATAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAKuIxbDD4mXNQqp6vc20JiRFpK
    1RXbsmIfbA4IH82qIdzQuxt8GnC7byIYusqPINOmILtho30YzwgIaSaGU1uufz1L
    9gwJf8BaiWENVOYHsQPgEtv2DS6lO4K5tZVVUlJPHncB6Jq3pRQmQQ4gZ/GG5LGZ
    qrQaL6050vyqH4k+0ggEhOLAgOL0Q1sIIUFCW/XfH/RByjzSfKM3W2zxZMG2cPWU
    Iapj+AG9mqSF/e2cPeEM5RFsUltp8BlWo5BENJn8iV5AVA0O73JVDEN64YYw3sgZ
    Qc9LYk/YYWB8kOrTIwaf0Qd4fekhrgQhK/2qfGZWqewghcKRM0hIM9OQd2uH
    -----END TRUSTED CERTIFICATE-----
