apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservices-pvc
  labels:
    app: authservices-db
spec:
  #storageClassName: db-storage-class
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
