apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userservices-pvc
  labels:
    app: userservices-db
spec:
  storageClassName: db-storage-class
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
