apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: jessthesaver/authservices
          #command: ["tail", "-f", "/dev/null"]
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: token
            - name: MONGO_URL
              value: mongodb://auth-db-svc:27017/
            - name: PORT
              value: "5000"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
