apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservices-deployment
  labels:
    app: userservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservices
  template:
    metadata:
      labels:
        app: userservices
    spec:
      containers:
        - name: userservices
          image: jessthesaver/userservices
          env:
            - name: MONGO_URL
              value: mongodb://userservices-db-svc:27017/
            - name: PORT
              value: "5500"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
