apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservices-db-deployment
  labels:
    app: authservices-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservices-db
  template:
    metadata:
      labels:
        app: authservices-db
    spec:
      volumes:
        - name: authservices-volume
          persistentVolumeClaim:
            claimName: authservices-pvc
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: authservices-volume
          resources:
            limits:
              memory: "512Mi"
              #cpu: "500m"
          ports:
            - containerPort: 27017
